name: Build and Test Server++

# Trigger the workflow on pull requests and pushes to main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ Compiler
      run: sudo apt-get install -y g++

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: ./build/your_executable_name
